config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  root "articles#index"

  resources :articles do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['private', 'public', 'archived']
  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates_uniqueness_of :email
  validates :email, email: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_user
    # ||= means if lhs is undefined or falsey evaluate rhs and assign it to lhs
    # Here this means @current_user is only evaluated once.
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  before_action :authorize, only: [:create, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  # by default, edit action renders app/views/articles/edit.html.erb
  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path, status: :see_other
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :status)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   # http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  before_action :authorize, only: [:create, :destroy]

  def create
    @article = Article.find(params[:article_id])
    # this takes advantage of the association between article and comment: this automatically links the comment so it belongs to the article
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: 303
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    flash[:referer] = request.referer
  end

  def create
    # this is where the actual authentication happens
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_path = (flash[:referer].nil? ? root_path : flash[:referer])
      redirect_to redirect_path, notice: "Logged in!", status: :see_other
    else
      flash.now.alert = "Email or password is invalid."
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    # alternatively
    # reset_session
    redirect_back_or_to root_path, notice: "Logged out", status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    flash[:referer] = request.referer
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_path = (flash[:referer].nil? ? root_path : flash[:referer])
      redirect_to redirect_path, notice: "Thank you for signing up!", status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
    <div class="field">
        <div><%= form.label :title %></div>
        <%= form.text_field :title %>
        <% article.errors.full_messages_for(:title).each do |message| %>
            <div class="error_messages"><%= message %></div>
        <% end %>
    </div>

    <div class="field">
        <div><%= form.label :body %></div>
        <%= form.text_area :body %>
        <% article.errors.full_messages_for(:body).each do |message| %>
            <div class="error_messages"><%= message %></div>
        <% end %>
    </div>

    <div class="field">
        <%= form.label :status %><br />
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>

    <div class="action">
        <%= form.submit %>
    </div>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<p>Our blog has <%= Article.public_count %> articles and counting!</p>
<ul>
    <% @articles.each do |article| %>
        <% unless article.archived? %>
            <li>
                <!-- <a href = "<%= article_path(article) %>"> -->
                <!--   <%= article.title %> -->
                <!-- </a> -->
                <%= link_to article.title, article %>
            </li>
        <% end %>
    <% end %>
</ul>


<div >
    <% if current_user %>
        <%= link_to "New Article", new_article_path, :class => 'btn'%>
    <% else %>
        To create a new article,
        <%= link_to "Sign up", signup_path %> or
        <%= link_to "Log in", login_path %>.
    <% end %>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<div >
    <% if current_user %>
        <p><%= link_to "Edit article", edit_article_path(@article), :class => 'btn' %></p>

        <p><%= link_to "Delete article", article_path(@article), :class => 'btn', data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
           } %>
        </p>
    <% else %>
        To edit or delete article,
        <%= link_to "Sign up", signup_path %> or
        <%= link_to "Log in", login_path %>.
    <% end %>
</div>



<h2>Comments</h2>
<!-- This will render the partial in app/views/comments/_comment.html.erb once for each comment that is in the @article.comments collection -->
<%= render @article.comments %>

<% if current_user %>
    <h2>Add a comment</h2>

    <%= render "comments/form" %>
<% else %>
    To add or delete a comment,
    <%= link_to "Sign up", signup_path %> or
    <%= link_to "Log in", login_path %>.
<% end %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
    <p>
        <%= comment.body %>
    </p>
    <p class="commenter">
        ~ <%= comment.commenter %>
    </p>

    <% if current_user %>
        <%= link_to "Delete comment", [comment.article, comment], :class => 'btn', data:
        {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
        } %>
    <% end %>
<% end %>

app/views/comments/_form.html.erb
<!-- form_with uses an array, which will build a nested route, such as /articles/1/comments. -->
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
        <div><%= form.label :commenter %></div>
        <%= form.text_field :commenter %>
    </p>
    <p>
        <div><%= form.label :body %></div>
        <%= form.text_area :body %>
    </p>
    <p>
        <%= form.label :status %></br>
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Blog</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
        <%= javascript_importmap_tags %>
    </head>

    <body>
        <div id="container" >
            <div class="flex-container">
                <div class="flex-child" id="home">
                    <%= link_to(root_path) do %>
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                            <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/>
                        </svg>
                    <% end %>
                </div>
                <div class="flex-child" id="user_header" >
                    <% if current_user %>
                        Logged in as <%= current_user.email %>
                        <%= link_to "Log out", logout_path, :class => 'btn' %>
                    <% else %>
                        <%= link_to "Sign up", signup_path, :class => 'btn' %> or
                        <%= link_to "Log in", login_path, :class => 'btn' %>
                    <% end %>
                </div>
            </div>

            <% flash.each do |name, msg| %>
                <% if name == "notice" || name == "alert" %>
                    <%= content_tag :div, msg, id: "flash_#{name}" %>
                <% end %>
            <% end %>

            <%= yield %>
        </div>
    </body>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages" >
            <h2>Form is invalid</h2>
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field" >
        <div><%= f.label :email %></div>
        <%= f.text_field :email %>
    </div>
    <div class="field" >
        <div><%= f.label :password %></div>
        <%= f.text_field :password %>
    </div>
    <div>
        <div><%= f.label :password_confirmation %></div>
        <%= f.text_field :password_confirmation %>
    </div>

    <div class="actions" ><%= f.submit %></div>
<% end %>